#!/bin/bash -l

#$-N wd_fuzzyGraph_tasks_prelude
#$-l mem_per_core=8G
#$-pe omp 16
#$-m a
#$-j y
#$-l h_rt=12:00:00
#-q !linga
#$-l cpu_arch=!bulldozer
#$-P salabs
#$-o logs

module load R/3.2.3

#Arguments
#1. weighted diameter threshold
#2. edge weight column (3, 4 or 5)
#3. number of groups

# run fuzzyGraph prelude in R, note 0.3 is chosen as a minimum threshold for fuzzyGraph_tasks_prelude
time Rscript wd_fuzzyGraph_tasks_prelude.R .3 3 50

